### ISSUE TITLE
Adding Verify Call

### ISSUE THREAD

**Issue by ardeay** [zesty-io/zestyio-node-api-wrapper#5]
This is how I hit verify user tokens on zesty.io marketing site, it passes the cookie as credentials, so this call in auth will need to be opened up to accept the token as a header for external verification @simonprickett 

```
async function verifyUserAndGetZUID(){
	return fetch('https://svc.zesty.io/auth/verify', {
		method: "GET",
		headers: {
			'Accept': 'application/json',
			'Content-Type': 'application/json',
			'Cache': 'no-cache'
		},
		credentials: 'include'
	}).then(function(response) {
		return response.json();
	}).then(function(json) {

		return json.meta.userZuid;
	});
}
```

Having a verify call will eliminate the need to login prior to every API call made externally

**Comment by simonprickett** [comment]
For now login and verify examples, including Authy One Touch 2FA can be seen here: https://github.com/zesty-io/node-login-example/

**Comment by simonprickett** [comment]
Verify call added as path of the auth work [here](https://github.com/zesty-io/zestyio-node-api-wrapper/blob/master/auth/index.js) and documented in README [here](https://github.com/zesty-io/zestyio-node-api-wrapper/blob/master/README.md).
